### ISSUE TITLE
It doesnt work

### ISSUE THREAD

**Issue by hungdev** [crypton-tech/react-native-scanner-zebra#2]
I don't know why it doesn't work

**Comment by MossPalmer-POL** [comment]
I don't know the answer to your problem but that has to be the least helpful issue I've ever seen raised. You will need to add a lot more info than that.. Does it build but then not recognise the scanner? Does it build the scan but fail to recognise the barcode? Does it build but the crash when you try to scan something? Does it fail to build? Are you using a bluetooth or wired scanner? You've provided zero info to enable anyone to help you.

**Comment by hungdev** [comment]
I tried to copy your example code to my app, but when I press scan button on zebra phone, it didn't return anything in 2 funcs: onScan and onEvent.
And I switched to another library and it worked for me: https://github.com/darryncampbell/react-native-datawedge-intents

**Comment by MossPalmer-POL** [comment]
It's not my library. I was just pointing out that the ticket wasn't helpful. As a guess I think your issue may have been that this library is currently only setup for bluetooth comms. Changing the comm type in the source code can fix it for other connections.
